### ISSUE TITLE
Collect the names of schools of users

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#132]
We're looking for a way to measure number of schools participating in pilots.

Could we force users to provide the name of their school in their user profile in Moodle?

Could users pick up the name from a list of already-provided names, or input the name manually if not in the list?

**Comment by athird** [comment]
@michzimny Not clearly, particularly as we're not really going through the Moodle registration process. Could this not be manually recorded by country coordinators, since they do need to authorise schools/teachers anyway (don't they?)? We could then in principle collect numbers of users per-school by looking at enrolment counts for courses associated with teachers from particular schools.
